<center>
<img src="./images/EAN.jpg" style="width:1200px">
</center>

<center>
<img src="./images/0_intro_ml.jpg" style="width:1200px">
</center>

# Lecture 1: Introduction to ML

## Instructors:

>Leonardo A. Espinosa, PhD. Instructor.
(*email*: leonardo.espinosaleal@arcada.fi)

> Ruben D. Acosta, MSc. Instructor.
(*email*:  rdacostav@universidadean.edu.co)

# Content

1\. <a href="#/5/1">Motivation</a>
   
2\. <a href="#/12/1">Why python?</a>
 
3\. <a href="#/50/1">Hands-on part: python libraries and setting-up everything is needed</a>
* <a href="#/31/1">Numpy</a>
* <a href="#/46/1">Scipy</a>
* <a href="#/51/1">Matplotlib</a>
* <a href="#/51/1">Pandas</a>
* <a href="#/51/1">Scikit-learn</a>

 

<center>
<img src="./images/ai_ml_dl.png" style="width:1400px">
</center>

# Motivation.

- Machine learning is about extracting knowledge from data.

- The application of machine learning methods has in recent years become ubiquitous in everyday life.

- Avoid handcoded rules. 

- Emergence of digital society.

<center>
<img src="./images/industria4.jpg" style="width:1400px">
</center>

>Digital twins, 5G, IoT, GPUs/APUs, among others.

<center>
    <img src="./images/ds_job.png" style="width:1200px">
    source: Forbes
</center>

<center>
    <img src="./images/Data-Science-Skills-Udacity-Matrix.png" style="width:1000px">
    source: Udacity
</center>

## Knowing Your Task and Knowing Your Data

* What question(s) am I trying to answer? Do I think the data collected can answer that question?
* What is the best way to phrase my question(s) as a machine learning problem?
* Have I collected enough data to represent the problem I want to solve?
* What features of the data did I extract, and will these enable the right predictions?
* How will I measure success in my application?
* How will the machine learning solution interact with other parts of my research or business product?

In a larger context, the algorithms and methods in machine learning are only one
part of a greater process to solve a particular problem, and it is good to keep the big
picture in mind at all times. Many people spend a lot of time building complex
machine learning solutions, only to find out they don’t solve the right problem.

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

<center>
    <img src="./images/python.png" style="width:1200px">
</center>

# Why Python?
* Python has become the lingua franca for many data science applications. 
* It combines the power of general-purpose programming languages with the ease of use of domain-specific scripting languages like MATLAB or R. 
* Python has libraries for data loading, visualization, statistics, natural language processing, image processing, and more.

<center>
    <img src="./images/scikit_learn.png" style="width:500px">
    https://scikit-learn.org
</center>

>Scikit-learn (formerly scikits.learn and also known as sklearn) is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy (from wiki).

How to install it?

<center>
    <img src="./images/00_hands-on.jpg" style="width:1000px">
    Hands-on!
</center>

# Installing Anaconda and ML python libraries.

A Python distribution made for large-scale data processing, predictive analytics, and scientific computing. Anaconda comes with NumPy, SciPy, matplotlib ,
pandas , IPython, Jupyter Notebook, and scikit-learn. Available on Mac OS, Windows, and Linux.

Steps:
1. https://www.anaconda.com/products/individual
2. Install the version 3 for your operative system (64-Bit).
3. Create a new python environment.
4. Install these packages: ``numpy, scipy, matplotlib, ipython, jupyter, scikit-learn, pandas``

### Jupyter Notebook

The Jupyter Notebook is an interactive environment for running code in the browser. It is a great tool for exploratory data analysis and is widely used by data scientists.

<center>
    <img src="./images/jupyter_logo.png" style="width:150px">
https://jupyter.org/
</center>



Developed by Fernando Pérez, physicist from Medellin. 

https://en.wikipedia.org/wiki/Fernando_P%C3%A9rez_(software_developer)

### Alternatives:

* Google Colaboratory: https://colab.research.google.com
* Azure notebooks: https://notebooks.azure.com/
* CoCalc: https://cocalc.com/
* Apache Zeppelin:  https://zeppelin.apache.org/

and many more!

## Colab time


<center>
    <img src="./images/colab.png" style="width:500px">
https://colab.research.google.com
</center>


   # Exercises

In [6]:
print('Hello world')

Hello world


In [9]:
x = 1
if x == 1:
    # indented four spaces
    print("x is 1.")

x is 1.



Python supports two types of numbers - integers and floating point numbers. (It also supports complex numbers).

In [10]:
myint = 7
print(myint)

7


To define a floating point number, you may use one of the following notations:

In [11]:
myfloat = 7.0
print(myfloat)
myfloat = float(7)
print(myfloat)


7.0
7.0


Strings are defined either with a single quote or a double quotes.

In [12]:
mystring = 'hello'
print(mystring)
mystring = "hello"
print(mystring)

mystring = "Don't worry about apostrophes"
print(mystring)

hello
hello
Don't worry about apostrophes


Simple operators can be executed on numbers and strings:

In [13]:
one = 1
two = 2
three = one + two
print(three)

hello = "hello"
world = "world"
helloworld = hello + " " + world
print(helloworld)

3
hello world


*Lists* are very similar to arrays. They can contain any type of variable, and they can contain as many variables as you wish. Lists can also be iterated over in a very simple manner. Here is an example of how to build a list.

In [16]:
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)
print(mylist[0]) # prints 1
print(mylist[1]) # prints 2
print(mylist[2]) # prints 3

# prints out 1,2,3
for xx in mylist:
    print(xx)

1
2
3
1
2
3


In [25]:
mylist = [1,2,3]
print(mylist[-1])

3


## Exercise

In this exercise, you will need to add numbers and strings to the correct lists using the "append" list method. You must add the numbers 1,2, and 3 to the "numbers" list, and the words 'hello' and 'world' to the strings variable.

You will also have to fill in the variable second_name with the second name in the names list, using the brackets operator []. Note that the index is zero-based, so if you want to access the second item in the list, its index will be 1.

In [26]:
numbers = []
strings = []
names = ["John", "Eric", "Jessica"]

# write your code here
second_name = names[1]
numbers.append(1)
numbers.append(2)
numbers.append(3)

strings.append('Hello')
strings.append('World')

# this code should write out the filled arrays and the second name in the names list (Eric).
print(numbers)
print(strings)
print("The second name on the names list is %s" % second_name)

[1, 2, 3]
['Hello', 'World']
The second name on the names list is Eric


## Arithmetic Operators

Just as any other programming languages, the addition, subtraction, multiplication, and division operators can be used with numbers.

In [27]:
number = 1 + 2 * 3 / 4.0
print(number)

2.5


In [28]:
remainder = 11 % 3
print(remainder)

2


In [29]:
squared = 7 ** 2
cubed = 2 ** 3
print(squared)
print(cubed)

49
8


# Using Operators with Strings

Python supports concatenating strings using the addition operator:

In [30]:
helloworld = "hello" + " " + "world"
print(helloworld)

hello world


Python also supports multiplying strings to form a string with a repeating sequence:

In [32]:
lotsofhellos = "hello " * 10
print(lotsofhellos)

hello hello hello hello hello hello hello hello hello hello 


# Using Operators with Lists

Lists can be joined with the addition operators:

In [33]:
even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]
all_numbers = odd_numbers + even_numbers
print(all_numbers)

[1, 3, 5, 7, 2, 4, 6, 8]


Just as in strings, Python supports forming new lists with a repeating sequence using the multiplication operator:

In [34]:
print([1,2,3] * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


# The *for* loop

For loops iterate over a given sequence. Here is an example:

In [36]:
primes = [2, 3, 5, 7]
for x in primes:
    print('primes: {}'.format(x))

primes: 2
primes: 3
primes: 5
primes: 7


In [38]:
for x in range(5):
    print(x)

print("")
# Prints out 3,4,5
for x in range(3, 6):
    print(x)

0
1
2
3
4

3
4
5


# Functions

In [41]:
# Define our 3 functions
def my_function():
    print("Hello From My Function!")

def my_function_with_args(username, greeting):
    print("Hello, %s , From My Function!, I wish you %s"%(username, greeting))

def my_function_with_args2(username, greeting):
    print("Hello, {} , From My Function!, I wish you {}".format(username, greeting))

    
def sum_two_numbers(a, b):
    return a + b

# print(a simple greeting)
my_function()

#prints - "Hello, John Doe, From My Function!, I wish you a great year!"
my_function_with_args("John Doe", 2)

# after this line x will hold the value 3!
x = sum_two_numbers(1,2)
print(x)

Hello From My Function!
Hello, John Doe , From My Function!, I wish you 2
3


# Other sources:

* https://www.python.org/
* https://wiki.python.org/moin/BeginnersGuide/Programmers
* https://www.w3schools.com/python/default.asp
* https://www.learnpython.org/
* https://www.codecademy.com/learn/learn-python-3

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

<img src="./images/NumPy.png" style="width:500px">
NumPy is one of the fundamental packages for scientific computing in Python. It contains functionality for multidimensional arrays, high-level mathematical functions such as linear algebra operations and the Fourier transform, and pseudorandom number generators.

The core functionality of NumPy is the ndarray class, a multidimensional ($n$-dimensional) array. All elements of the array must be of the same type. (https://numpy.org/)

In [2]:
import numpy as np

x1 = np.array([0, 1, 2, 3])
x2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1d:\n{}".format(x1))
print("2d:\n{}".format(x2))

1d:
[0 1 2 3]
2d:
[[1 2 3]
 [4 5 6]]


In [7]:
x2.shape

(2, 3)

In [8]:
x2.shape

(2, 3)

### NumPy provides:

* extension package to Python for multi-dimensional arrays
* closer to hardware (efficiency)
* designed for scientific computation (convenience)
* Also known as *array oriented computing*

**Why it is useful**: Memory-efficient container that provides fast numerical operations.

In [9]:
L = range(1000)

In [10]:
%timeit [i**2 for i in L]

457 µs ± 27.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
a = np.arange(1000)
%timeit a**2

2.74 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### NumPy Reference documentation

* On the web: http://docs.scipy.org/

* Interactive help:

In [12]:
np.array?

* Looking for something:

In [14]:
np.lookfor('create array') 

/bin/sh: 1: Syntax error: word unexpected (expecting ")")


In [15]:
np.con*?

### Functions for creating arrays

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.linspace(0, 1, 6)
b

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
c = np.ones((3, 3)) 
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
r = np.random.rand(4)
r

array([0.13764496, 0.58244795, 0.35906393, 0.41272275])

### Basic data types

In [20]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [21]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

In [22]:
c = np.array([1, 2, 3], dtype='float16')
c.dtype

dtype('float16')

<center>
<img src="./images/NumPy_types.png" style="width:1200px">
</center>

### Indexing and slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [23]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[0], a[2], a[-1]

(0, 2, 9)

In [25]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
b = np.diag(np.arange(3))
b

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [29]:
b[2, 2]

2

In [30]:
b[2, 1] = 10 # third line, second column
b

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [31]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
c[2:9:3] # [start:end:step]

array([2, 5, 8])

In [33]:
c[:4]

array([0, 1, 2, 3])

## Exercise: Creating arrays using functions

* Experiment with *arange*, *linspace*, *ones*, *zeros*, *eye* and *diag*.
* Create different kinds of arrays with random numbers.
* Try setting the seed before creating an array with random values.
* Look at the function *np.empty*. What does it do? When might this be useful?

<center>
<img src="./images/NumPy_slicing.png" style="width:1400px">
</center>

<center>
<img src="./images/NumPy_slicing2.png" style="width:1500px">
</center>

### Exercise: Indexing and slicing

* Try the different flavours of slicing, using *start*, *end* and *step*: starting from a linspace, try to obtain odd numbers counting backwards, and even numbers counting forwards.

* Reproduce the slices in the diagram above. You may use the following expression to create the array:

In [ ]:
np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

<img src="./images/scipy.png" style="width:500px">
SciPy is a collection of functions for scientific computing in Python. It provides, among other functionality, advanced linear algebra routines, mathematical function optimization, signal processing, special mathematical functions, and statistical distributions (https://www.scipy.org/scipylib/index.html).

Usually it is not possible to create dense representations of sparse data (as they would
not fit into memory), so we need to create sparse representations directly. Here is a
way to create the same sparse matrix as before, using the COO format:

In [ ]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n{}".format(eye_coo))

<center>
    <img src="./images/Scipy_functions.png" style="width:1000px">
</center>

In [ ]:
from scipy import linalg

arr = np.array([[1, 2], [3, 4]])
arr

In [ ]:
linalg.det(arr)

In [ ]:
iarr = linalg.inv(arr)
iarr

In [ ]:
np.dot(arr,iarr)

More details on SciPy sparse matrices can be found in the SciPy Lecture Notes: http://scipy-lectures.org/

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

<img src="./images/matplotlib.png" style="width:500px">
matplotlib is the primary scientific plotting library in Python. It provides functions for making publication-quality visualizations such as line charts, histograms, scatter plots, and so on.

Visualizing your data and different aspects of your analysis can give you important insights.

https://matplotlib.org/

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
# Generate a sequence of numbers from -10 to 10 with 100 steps in between
x = np.linspace(-10, 10, 100)
# Create a second array using sine
y = np.sin(x)
# The plot function makes a line chart of one array against another
plt.plot(x, y, marker="x")

### Other more advanced visualization libraries

* *Seaborn*:  Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics (https://seaborn.pydata.org/).
* *ggplot*: is a plotting system for Python based on R's ggplot2 and the Grammar of Graphics. It is built for making profressional looking, plots quickly with minimal code (http://ggplot.yhathq.com/).
* *Bokeh*: Bokeh is an interactive visualization library for modern web browsers. It provides elegant, concise construction of versatile graphics, and affords high-performance interactivity over large or streaming datasets. Bokeh can help anyone who would like to quickly and easily make interactive plots, dashboards, and data applications (https://docs.bokeh.org).
* *Plotly*: Plotly's Python graphing library makes interactive, publication-quality graphs. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts (https://plotly.com/python/).

In [ ]:
import plotly.express as px
df = px.data.tips()

fig = px.density_heatmap(df, x="total_bill", y="tip")
fig.show()

Now let's do a mix of everything:

In [ ]:
def f(x):
    return x**2 + 10*np.sin(x)

x = np.arange(-10, 10, 0.1)
plt.plot(x, f(x)) 
plt.show()

In [ ]:
from scipy.optimize import minimize

result = minimize(f, x0=0)
result

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

### Exercise: 2-D minimization


The six-hump camelback function $f(x, y) = (4 - 2.1x^2 + \frac{x^4}{3})x^2 + xy + (4y^2 - 4)y^2$ has multiple global and local minima. Find the global minima of this function.

Hints:

* Variables can be restricted to -2 < x < 2 and -1 < y < 1.
* Use numpy.meshgrid() and matplotlib.pyplot.imshow() to find visually the regions.
* Use scipy.optimize.minimize(), optionally trying out several of its `methods’.

How many global minima are there, and what is the function value at those points? What happens for an initial guess of (x, y) = (0, 0) ?

<img src="./images/Pandas_logo.png" style="width:500px">

Pandas is a Python library for data wrangling and analysis. It is built around a data structure called the *DataFrame* that is modeled after the **R** DataFrame.

A pandas DataFrame is a table, similar to an Excel spreadsheet. pandas provides a great range of methods to modify and operate on this table; in particular, it allows SQL-like queries and joins of tables.

More https://pandas.pydata.org/

In [ ]:
import pandas as pd
# create a simple dataset of people
data = {'Name': ["John", "Anna", "Peter", "Linda"],
'Location' : ["New York", "Paris", "Berlin", "London"],
'Age' : [24, 13, 53, 33]
}
data_pandas = pd.DataFrame(data)
# IPython.display allows "pretty printing" of dataframes
# in the Jupyter notebook
display(data_pandas)

In [ ]:
# Select all rows that have an age column greater than 30
display(data_pandas[data_pandas.Age > 30])

In [ ]:
# Read data from files
! more data/data.csv

In [ ]:
df = pd.read_csv('data/data.csv')
df

In [ ]:
df.iloc[::1]

In [ ]:
df2 = df.drop(df.columns[[0]], axis=1)
df2

In [ ]:
df2['new'] = 1
df2

### Slicing dataframes

In [ ]:
df2.iloc[:,:2]

In [ ]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
df_a = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_a

In [ ]:
raw_data2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
df_b = pd.DataFrame(raw_data2, columns = ['subject_id', 'first_name', 'last_name'])
df_b

In [ ]:
df_new = pd.concat([df_a, df_b])
df_new

In [ ]:
# More advanced features:

df3 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=';')

In [ ]:
df3

In [ ]:
df3.head()

In [ ]:
df3.tail()

In [ ]:
df3.describe()

In [ ]:
df3.columns

In [ ]:
df3.dtypes

In [ ]:
df3.info()

### Extract numpy values from dataframes


In [ ]:

np_df3 = df3.values

In [ ]:
np_df3

### Exercise

* Got to https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/
* Create a dataframe for the white wine.
* Create a new column for the red wine dataframe equal to 0 and a new column for the white wine equal to 1, name it as "type"
* Concatenate the two obtained dataframes.

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

# A First Machine Learning Model

<center>
    <img src="./images/iris.png" style="width:1200px">
    <img src="./images/iris_cm.jpg" style="width:200px">
    The Iris dataset
</center>




### Meet the Data

The data we will use for this example is the Iris dataset, a classical dataset in machine learning and statistics. It is included in scikit-learn in the datasets module. We can load it by calling the load_iris function:

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("Type {}".format(type(iris_dataset)))

In [ ]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

In [ ]:
#Check what is inside the da

### Measuring Success: Training and Testing Data

* We want to build a machine learning model from this data that can predict the species of iris for a new set of measurements.

* before we can apply our model to new measurements, we need to know whether it actually works.

* We cannot use the data we used to build the model to evaluate it

* We need to split our data to evaluate the performance of the trained model. *Scikit-learn* contains a function for this:

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

In [ ]:
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

## First Things First: Look at Your Data

Before building a machine learning model it is often a good idea to inspect the data, to see if the task is easily solvable without machine learning, or if the desired information might not be contained in the data.

Inspecting your data is a good way to find abnormalities and peculiarities. Maybe some of your irises were measured using inches and not centimeters, for
example. In the real world, inconsistencies in the data and unexpected measurements are very common.

<center>
    <img src="./images/real_ds.jpg" style="width:1200px">
    Source: Forbes
</center>

In [ ]:
import mglearn
# create dataframe from data in X_train
# label the columns using the strings in iris_dataset.feature_names
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
# create a scatter matrix from the dataframe, color by y_train
grr = pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o', hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

### Building Your First Model: k-Nearest Neighbors

Now we can start building the actual machine learning model. There are many classification algorithms in scikit-learn that we could use. Here we will use a $k$-nearest neighbors classifier, which is easy to understand.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(X_train, y_train)

### Making Predictions

In [ ]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

In [ ]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(iris_dataset['target_names'][prediction]))

### Evaluating the Model

This is where the test set that we created earlier comes in. This data was not used to build the model, but we do know what the correct species is for each iris in the test set.

In [ ]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

In [ ]:
print("Test set score: {:.2f}".format(np.mean(y_pred == y_test)))

In [ ]:
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))

<center>
    <img src="./images/00_questions.jpg" style="width:1200px">
</center>

# Conclusions

* Machine learning is the sexiest job of the 21 century.
* Python is the lingua franca for data science. 
* Scikit-learn is the battle horse for machine learning.